#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

JOBS="${JOBS:-$(nproc)}"
CC="${AARCH64_CC:-aarch64-linux-gnu-gcc}"
CROSS_PREFIX="${AARCH64_CROSS_PREFIX:-aarch64-linux-gnu-}"
EMBENCH_DIR="${EMBENCH_DIR:-$ROOT/benchmarks/external/embench-iot}"
EMBENCH_BUILD="${EMBENCH_BUILD:-$EMBENCH_DIR/bd-a64-gem5}"
EMBENCH_LOGS="${EMBENCH_LOGS:-$EMBENCH_DIR/logs-a64-gem5}"
EMBENCH_COMMIT="0466a18e4f6b47e19598d7c6ba72916d54b68f65"
M5LIB="$ROOT/util/m5/build/arm64/out/libm5.a"

if ! command -v "$CC" >/dev/null 2>&1; then
  echo "ERROR: AArch64 Linux cross compiler not found: $CC" >&2
  exit 2
fi

echo "[1/4] Build AArch64 libm5"
scons -C util/m5 \
  "arm64.CROSS_COMPILE=$CROSS_PREFIX" \
  build/arm64/out/libm5.a \
  -j"$JOBS"

if [[ ! -f "$M5LIB" ]]; then
  echo "ERROR: expected libm5 missing: $M5LIB" >&2
  exit 2
fi

echo "[2/4] Fetch exact Embench source revision"
mkdir -p "$(dirname "$EMBENCH_DIR")"
if [[ ! -d "$EMBENCH_DIR/.git" ]]; then
  git clone https://github.com/embench/embench-iot.git "$EMBENCH_DIR"
else
  git -C "$EMBENCH_DIR" fetch --tags origin
fi

git -C "$EMBENCH_DIR" checkout --detach "$EMBENCH_COMMIT"
actual="$(git -C "$EMBENCH_DIR" rev-parse HEAD)"
if [[ "$actual" != "$EMBENCH_COMMIT" ]]; then
  echo "ERROR: Embench revision mismatch: $actual" >&2
  exit 2
fi

echo "[3/4] Install gem5 ROI board shim"
ARCHDIR="$EMBENCH_DIR/config/arm64linux"
CHIPDIR="$ARCHDIR/chips/generic"
BOARDDIR="$ARCHDIR/boards/gem5"
mkdir -p "$CHIPDIR" "$BOARDDIR"

cat >"$ARCHDIR/arch.cfg" <<'EOF'
# Generated by gem5 scripts/a64_embench_prepare.sh.
# Toolchain and ISA flags are supplied explicitly on build_all.py CLI.
EOF

cat >"$ARCHDIR/archsupport.c" <<'EOF'
/* Intentionally empty: creates Embench's AArch64 support build directory. */
EOF

cat >"$CHIPDIR/chip.cfg" <<'EOF'
# Generated generic AArch64 Linux chip configuration.
EOF

cat >"$CHIPDIR/chipsupport.c" <<'EOF'
/* Intentionally empty: creates Embench's generic chip support build directory. */
EOF

cat >"$BOARDDIR/board.cfg" <<'EOF'
# Generated gem5 board configuration.
cpu_mhz = 1
warmup_heat = 1
EOF

cat >"$BOARDDIR/boardsupport.c" <<'EOF'
#include <gem5/m5ops.h>
#include <support.h>

void
initialise_board(void)
{
}

void __attribute__((noinline)) __attribute__((externally_visible))
start_trigger(void)
{
    m5_reset_stats(0, 0);
}

void __attribute__((noinline)) __attribute__((externally_visible))
stop_trigger(void)
{
    m5_dump_stats(0, 0);
}
EOF

cat >"$BOARDDIR/boardsupport.h" <<'EOF'
#ifndef EMBENCH_GEM5_A64_BOARDSUPPORT_H
#define EMBENCH_GEM5_A64_BOARDSUPPORT_H
#define CPU_MHZ 1
#endif
EOF

echo "[4/4] Build Embench for static AArch64 GNU/Linux"
CFLAGS="-c -O2 -march=armv8-a -fdata-sections -ffunction-sections -I$ROOT/include"
LDFLAGS="-O2 -static -march=armv8-a -Wl,-gc-sections"
USER_LIBS="$M5LIB -lm"

(
  cd "$EMBENCH_DIR"
  python3 build_all.py \
    --builddir="$EMBENCH_BUILD" \
    --logdir="$EMBENCH_LOGS" \
    --arch=arm64linux \
    --chip=generic \
    --board=gem5 \
    --cc="$CC" \
    --ld="$CC" \
    --cflags="$CFLAGS" \
    --ldflags="$LDFLAGS" \
    --user-libs="$USER_LIBS" \
    --cpu-mhz=1 \
    --warmup-heat=1 \
    --timeout=120 \
    --clean
)

WORKLOADS=(
  matmult-int
  nettle-sha256
  nettle-aes
  sglib-combined
  wikisort
  picojpeg
)

for w in "${WORKLOADS[@]}"; do
  bin="$EMBENCH_BUILD/src/$w/$w"
  if [[ ! -x "$bin" ]]; then
    echo "ERROR: missing Embench binary: $bin" >&2
    exit 3
  fi
  if ! file "$bin" | grep -q 'ARM aarch64'; then
    echo "ERROR: unexpected binary architecture for $w" >&2
    file "$bin" >&2
    exit 3
  fi
  file "$bin"
done

echo
echo "EMBENCH_DIR=$EMBENCH_DIR"
echo "EMBENCH_BUILD=$EMBENCH_BUILD"
echo "EMBENCH_HEAD=$actual"
echo "M5LIB=$M5LIB"
"$CC" --version | head -n 1
