#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

JOBS="${JOBS:-$(nproc)}"
CC="${RISCV64_CC:-riscv64-linux-gnu-gcc}"
CROSS_PREFIX="${RISCV64_CROSS_PREFIX:-riscv64-linux-gnu-}"
EMBENCH_DIR="${EMBENCH_DIR:-$ROOT/benchmarks/external/embench-iot}"
EMBENCH_BUILD="${EMBENCH_BUILD:-$EMBENCH_DIR/bd-rv64-gem5}"
EMBENCH_COMMIT="0466a18e4f6b47e19598d7c6ba72916d54b68f65"
M5LIB="$ROOT/util/m5/build/riscv/out/libm5.a"

if ! command -v "$CC" >/dev/null 2>&1; then
  echo "ERROR: RISC-V Linux cross compiler not found: $CC" >&2
  exit 2
fi

echo "[1/4] Build RV64 libm5"
scons -C util/m5   "riscv.CROSS_COMPILE=$CROSS_PREFIX"   build/riscv/out/libm5.a   -j"$JOBS"

if [[ ! -f "$M5LIB" ]]; then
  echo "ERROR: expected libm5 missing: $M5LIB" >&2
  exit 2
fi

echo "[2/4] Fetch exact Embench source revision"
mkdir -p "$(dirname "$EMBENCH_DIR")"
if [[ ! -d "$EMBENCH_DIR/.git" ]]; then
  git clone https://github.com/embench/embench-iot.git "$EMBENCH_DIR"
else
  git -C "$EMBENCH_DIR" fetch --tags origin
fi

git -C "$EMBENCH_DIR" checkout --detach "$EMBENCH_COMMIT"
actual="$(git -C "$EMBENCH_DIR" rev-parse HEAD)"
if [[ "$actual" != "$EMBENCH_COMMIT" ]]; then
  echo "ERROR: Embench revision mismatch: $actual" >&2
  exit 2
fi

echo "[3/4] Install gem5 ROI board shim"
ARCHDIR="$EMBENCH_DIR/config/riscv64linux"
CHIPDIR="$ARCHDIR/chips/generic"
BOARDDIR="$ARCHDIR/boards/gem5"
mkdir -p "$CHIPDIR" "$BOARDDIR"

cat >"$ARCHDIR/arch.cfg" <<'EOF'
# Generated by gem5 scripts/rv64_embench_prepare.sh.
# Toolchain and ISA flags are supplied explicitly on build_all.py CLI.
EOF

cat >"$CHIPDIR/chip.cfg" <<'EOF'
# Generated generic RV64 Linux chip configuration.
EOF

cat >"$BOARDDIR/board.cfg" <<'EOF'
# Generated gem5 board configuration.
cpu_mhz = 1
warmup_heat = 1
EOF

cat >"$BOARDDIR/boardsupport.c" <<'EOF'
#include <gem5/m5ops.h>
#include <support.h>

void
initialise_board(void)
{
}

void __attribute__((noinline)) __attribute__((externally_visible))
start_trigger(void)
{
    m5_reset_stats(0, 0);
}

void __attribute__((noinline)) __attribute__((externally_visible))
stop_trigger(void)
{
    m5_dump_stats(0, 0);
}
EOF

cat >"$BOARDDIR/boardsupport.h" <<'EOF'
#ifndef EMBENCH_GEM5_BOARDSUPPORT_H
#define EMBENCH_GEM5_BOARDSUPPORT_H
#define CPU_MHZ 1
#endif
EOF

echo "[4/4] Build Embench for static RV64 GNU/Linux"
CFLAGS="-c -O2 -march=rv64imafd -mabi=lp64d -fdata-sections -ffunction-sections -I$ROOT/include"
LDFLAGS="-O2 -static -march=rv64imafd -mabi=lp64d -Wl,-gc-sections"
USER_LIBS="$M5LIB -lm"

(
  cd "$EMBENCH_DIR"
  python3 build_all.py     --builddir="$EMBENCH_BUILD"     --logdir="$EMBENCH_BUILD/logs"     --arch=riscv64linux     --chip=generic     --board=gem5     --cc="$CC"     --ld="$CC"     --cflags="$CFLAGS"     --ldflags="$LDFLAGS"     --user-libs="$USER_LIBS"     --cpu-mhz=1     --warmup-heat=1     --timeout=120     --clean
)

WORKLOADS=(
  matmult-int
  nettle-sha256
  nettle-aes
  sglib-combined
  wikisort
  picojpeg
)

for w in "${WORKLOADS[@]}"; do
  bin="$EMBENCH_BUILD/benchmarks/$w/$w"
  if [[ ! -x "$bin" ]]; then
    echo "ERROR: missing Embench binary: $bin" >&2
    exit 3
  fi
  file "$bin"
done

echo
echo "EMBENCH_DIR=$EMBENCH_DIR"
echo "EMBENCH_BUILD=$EMBENCH_BUILD"
echo "EMBENCH_HEAD=$actual"
echo "M5LIB=$M5LIB"
"$CC" --version | head -n 1
